# AirBnB NY Locations Data Case Study

Your task will be to take the data provided and find evidence to answer the following questions.

1. Which hosts are the busiest and why?
2. How many neighborhood groups are available and which shows up the most?
3. Are private rooms the most popular in manhattan?
4. Which hosts are the busiest and based on their reviews?
5. Which neighorhood group has the highest average price?
6. Which neighborhood group has the highest total price?
7. Which top 5 hosts have the highest total price?
8. Who currently has no (zero) availability with a review count of 100 or more?
9. What host has the highest total of prices and where are they located?
10. When did Danielle from Queens last receive a review?

This is to simulate what you will face when you are out in the wild. 

Happy Coding!

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
air_bnb = pd.read_csv('./AB_NYC_2019.csv')

In [3]:
air_bnb.dropna(inplace=True)

In [4]:
#1. Which hosts are the busiest and why?
air_bnb.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38821 entries, 0 to 48852
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              38821 non-null  int64
 1   name                            38821 non-null  object
 2   host_id                         38821 non-null  int64
 3   host_name                       38821 non-null  object
 4   neighbourhood_group             38821 non-null  object
 5   neighbourhood                   38821 non-null  object
 6   latitude                        38821 non-null  float64
 7   longitude                       38821 non-null  float64
 8   room_type                       38821 non-null  object
 9   price                           38821 non-null  int64
 10  minimum_nights                  38821 non-null  int64
 11  number_of_reviews               38821 non-null  int64
 12  last_review                     38821 non-null  object
 13  reviews_per_month               38821 non-null  float64
 14  calculated_host_listings_count  38821 non-null  int64
 15  availability_365                38821 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 5.0+ MB

In [5]:
#2. How many neighborhood groups are available and which shows up the most?
air_bnb.neighbourhood_group.value_counts()

#ANSWER: There are 5 neighborhood groups and Manhatten shows up the most

Manhattan        16621
Brooklyn         16439
Queens            4572
Bronx              875
Staten Island      314
Name: neighbourhood_group, dtype: int64

In [6]:
#3. Are private rooms the most popular in manhattan?
manhattan = air_bnb.query("neighbourhood_group == 'Manhattan'")

manhattan.room_type.value_counts()


#ANSWER: No, Entire home/apt is the most popular in Manhattan.

Entire home/apt    9962
Private room       6303
Shared room         356
Name: room_type, dtype: int64

In [7]:
#4. Which hosts are the busiest and based on their reviews?

In [8]:
#5. Which neighorhood group has the highest average price?
air_bnb.groupby('neighbourhood_group').price.mean()

#ANSWER: Manahattan has the highest average price.

neighbourhood_group
Bronx             79.558857
Brooklyn         121.463289
Manhattan        180.071596
Queens            95.783683
Staten Island     89.964968
Name: price, dtype: float64

In [9]:
#6. Which neighbor hood group has the highest total price?

air_bnb.groupby('neighbourhood_group').price.max()


#ANSWER: Brooklyn and Queens have the highest total price.

neighbourhood_group
Bronx              800
Brooklyn         10000
Manhattan         9999
Queens           10000
Staten Island      625
Name: price, dtype: int64

In [21]:
#7. Which top 5 hosts have the highest total price?
# highest = air_bnb.groupby('host_id').price.sum()
# highest.sort_values

<bound method Series.sort_values of host_id
2438          95
2571         182
2787         604
2845         324
2868          60
            ...
272557707     65
272816114    170
272872092     16
273361532    110
273841667    100
Name: price, Length: 30232, dtype: int64>

In [11]:
#8.  Who currently has no (zero) availability with a review count of 100 or more?
who = air_bnb.query('availability_365 == 0 and number_of_reviews > 100')
who

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
8,5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80178,-73.96723,Private room,79,2,118,2017-07-21,0.99,1,0
94,20913,Charming 1 bed GR8 WBurg LOCATION!,79402,Christiana,Brooklyn,Williamsburg,40.70984,-73.95775,Entire home/apt,100,5,168,2018-07-22,1.57,1,0
132,30031,NYC artists’ loft with roof deck,129352,Sol,Brooklyn,Greenpoint,40.73494,-73.95030,Private room,50,3,193,2019-05-20,1.86,1,0
174,44221,Financial District Luxury Loft,193722,Coral,Manhattan,Financial District,40.70666,-74.01374,Entire home/apt,196,3,114,2019-06-20,1.06,1,0
180,45556,"Fort Greene, Brooklyn: Center Bedroom",67778,Doug,Brooklyn,Fort Greene,40.68863,-73.97691,Private room,65,2,206,2019-06-30,1.92,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29581,22705516,The Quietest Block in Manhattan :),127740507,Kathleen,Manhattan,Harlem,40.83102,-73.94181,Private room,65,2,103,2019-07-07,5.89,2,0
30461,23574142,queens get away!!,176185168,Janet,Queens,Laurelton,40.68209,-73.73662,Private room,65,1,119,2018-12-24,7.79,1,0
31250,24267706,entire sunshine of the spotless mind room,21074914,Albert,Brooklyn,Bedford-Stuyvesant,40.68234,-73.91318,Private room,49,1,102,2019-07-05,6.73,3,0
32670,25719044,COZY Room for Female Guests,40119874,Stephany,Brooklyn,Prospect-Lefferts Gardens,40.66242,-73.94417,Private room,48,1,131,2019-05-31,9.97,2,0
35014,27759146,Cozy corner near Empire State Building,209549523,Mariluz,Manhattan,Midtown,40.74858,-73.98341,Shared room,62,1,112,2019-06-13,10.77,3,0

In [12]:
#9. What host has the highest total of prices and where are they located?

In [19]:
#10. When did Danielle from Queens last receive a review?
danielle = air_bnb.query("host_name == 'Danielle' and neighbourhood_group == 'Queens'")

danielle.last_review

#ANSWER: July 8th, 2019

7086     2019-07-03
20403    2019-07-06
21517    2019-07-07
22068    2019-07-06
22469    2019-07-08
27021    2018-01-02
33861    2019-06-20
Name: last_review, dtype: object

## Further Questions

1. Which host has the most listings?

In [17]:
most = air_bnb.sort_values('calculated_host_listings_count', axis=0, ascending=False)
most.head()
#ANSWER = Sonder

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
43555,33716426,Sonder | Stock Exchange | Central 1BR + Kitchen,219517861,Sonder (NYC),Manhattan,Financial District,40.70723,-74.01086,Entire home/apt,229,2,3,2019-06-13,1.55,327,340
41418,32237768,Sonder | Stock Exchange | Bright 1BR + Laundry,219517861,Sonder (NYC),Manhattan,Financial District,40.70656,-74.01092,Entire home/apt,227,2,8,2019-06-05,1.88,327,356
41448,32239950,Sonder | Stock Exchange | Playful 1BR + Sofa Bed,219517861,Sonder (NYC),Manhattan,Financial District,40.70595,-74.01180,Entire home/apt,244,2,2,2019-06-14,1.82,327,317
41447,32239944,Sonder | Stock Exchange | Unique 1BR + Sofa Bed,219517861,Sonder (NYC),Manhattan,Financial District,40.70702,-74.01087,Entire home/apt,236,2,9,2019-06-05,2.52,327,347
41446,32239738,Sonder | Stock Exchange | Lively 1BR + Laundry,219517861,Sonder (NYC),Manhattan,Financial District,40.70563,-74.01097,Entire home/apt,227,2,3,2019-04-27,0.81,327,350

2. How many listings have completely open availability?

3. What room_types have the highest review numbers?

In [15]:
air_bnb.groupby('room_type').number_of_reviews.count()

#ANSWER: Entire Home

room_type
Entire home/apt    20321
Private room       17654
Shared room          846
Name: number_of_reviews, dtype: int64

# Final Conclusion

In this cell, write your final conclusion for each of the questions asked.

Also, if you uncovered some more details that were not asked above, please discribe them here.

-- Add your conclusion --